# Generated by Django 4.0.3 on 2022-04-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('status', models.TextField()),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
    ]
